server:
  port: 8082

spring:
  application:
    name: socio-service

  datasource:
    url: jdbc:postgresql://ep-sparkling-fog-aqjfhggu-pooler.c-8.us-east-1.aws.neon.tech/apr_socio_db?sslmode=require
    username: neondb_owner
    password: npg_LBdpGJT3ZQ1j

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
